import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>CollaborateCart</h1>
        <nav>
          <ul>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Как это работает</a></li>
            <li><a href="#">Преимущества</a></li>
            <li><a href="#">Контакты</a></li>
          </ul>
        </nav>
      </header>
      <section className="hero">
        <div className="hero-text">
          <h2>Покупайте оптом вместе</h2>
          <p>Совместные покупки - это просто, удобно и выгодно. Присоединяйтесь к нашей платформе и экономьте вместе с нами!</p>
          <button>Присоединиться сейчас</button>
        </div>
      </section>
      <section className="features">
        <div className="feature">
          <Image src="/assets/images/discount.svg" width={150} height={150} alt="Feature Icon"/>
          <h3>Больше скидок</h3>
          <p>Совместные покупки позволяют получить скидки на оптовые закупки, которых не смог бы получить один человек.</p>
        </div>
        <div className="feature">
          <Image src="/assets/images/click.svg" width={150} height={150} alt="Feature Icon"/>
          <h3>Просто и удобно</h3>
          <p>Платформа CollaborateCart очень проста в использовании. Присоединяйтесь к группам покупателей и получайте скидки уже сегодня.</p>
        </div>
        <div className="feature">
          <Image src="/assets/images/shield.svg" width={150} height={150} alt="Feature Icon"/>
          <h3>Безопасность</h3>
          <p>Мы гарантируем безопасность ваших данных и платежей. CollaborateCart - это надежная платформа для совместных покупок.</p>
        </div>
      </section>
      <section className="cta">
        <h2>Присоединяйтесь к нам уже сегодня!</h2>
        <button>Присоединиться сейчас</button>
      </section>
      <footer>
        <nav>
          <ul>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Как это работает</a></li>
            <li><a href="#">Преимущества</a></li>
            <li><a href="#">Контакты</a></li>
          </ul>
        </nav>
        <p>Photo by <a href="https://unsplash.com/@egla?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Hannes Egler</a> on <a href="https://unsplash.com/photos/nT4k2JDtwTQ?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></p>
        <p>© 2023 CollaborateCart. Все права защищены.</p>
      </footer>
    </>
  )
}
